# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build: 
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies    
      - run:
          name: install dependencies
          command: npm install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: npx nx build admin-ui
  test:
    docker:
      - image: cimg/node:14.17.0
    steps:
      # run test suite
      - run:
          name: test
          command: npx nx run-many --target=test --all=true
workflows:
  build_and_test:
    jobs:
      - build
      - test:
         requires:
           - build