# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      build_and_test:
        docker:
          - image: cimg/node:16.11.1
        steps:
          - checkout
          # look for existing cache and restore if found
          - restore_cache:
              key: v1-deps-{{ checksum "package-lock.json" }}
          # install dependencies    
          - run:
              name: install dependencies
              command: npm install
          # save any changes to the cache
          - save_cache:
              key: v1-deps-{{ checksum "package-lock.json" }}
              paths:
                - node_modules
          # run test suite
          - run:
              name: test
              command: npm run test
