# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  workspace-executor:
    docker:
      - image: cimg/node:14.17.0
    working_directory: /tmp/workspace

jobs:
  setup:
    executor: workspace-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies    
      - run:
          name: install dependencies
          command: npm install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  build: 
    executor: workspace-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: build
          command: npx nx build admin-ui
  test:
    executor: workspace-executor
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # run test suite
      - run:
          name: test
          command: npx nx test admin-ui
workflows:
  build_and_test:
    jobs:
      - test
      - build:
         requires:
           - test